name: "Archive Code"
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - run: zip -r fcmcleaner.zip *
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: fcm-cleaner-artifact
          path: fcmcleaner.zip
